name: depaneur_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  firebase_ui_auth: ^1.5.0
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.1
  image_picker: ^1.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - images/accedents.png
     - images/dep.png
     - images/user.png
     - images/remarque.webp
     - images/pneu.png
     - images/autre.png
